/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module storage_4 (
    input clk,
    input buta,
    input butb,
    input [15:0] switches,
    output reg [15:0] geta,
    output reg [15:0] getb
  );
  
  
  
  wire [1-1:0] M_eda_out;
  reg [1-1:0] M_eda_in;
  edge_detector_13 eda (
    .clk(clk),
    .in(M_eda_in),
    .out(M_eda_out)
  );
  wire [1-1:0] M_edb_out;
  reg [1-1:0] M_edb_in;
  edge_detector_13 edb (
    .clk(clk),
    .in(M_edb_in),
    .out(M_edb_out)
  );
  
  wire [1-1:0] M_button_condA_out;
  button_conditioner_15 button_condA (
    .clk(clk),
    .in(buta),
    .out(M_button_condA_out)
  );
  
  wire [1-1:0] M_button_condB_out;
  button_conditioner_15 button_condB (
    .clk(clk),
    .in(butb),
    .out(M_button_condB_out)
  );
  
  reg [15:0] M_storeA_d, M_storeA_q = 1'h0;
  
  reg [15:0] M_storeB_d, M_storeB_q = 1'h0;
  
  always @* begin
    M_storeB_d = M_storeB_q;
    M_storeA_d = M_storeA_q;
    
    M_eda_in = M_button_condA_out;
    M_edb_in = M_button_condB_out;
    if (M_eda_out) begin
      M_storeA_d = switches;
    end
    if (M_edb_out) begin
      M_storeB_d = switches;
    end
    geta = M_storeA_q;
    getb = M_storeB_q;
  end
  
  always @(posedge clk) begin
    M_storeB_q <= M_storeB_d;
  end
  
  
  always @(posedge clk) begin
    M_storeA_q <= M_storeA_d;
  end
  
endmodule
